[build-system]
requires = ["setuptools==65.6.3"]
build-backend = "setuptools.build_meta"

[project]
name = "nerfview"
version = "0.0.0"
authors = []
requires-python = ">=3.8"
dependencies = ["viser==0.2.0", "jaxtyping"]

[project.optional-dependencies]
examples = [
  "tyro",
  "torch",
  "nvdiffrast @ git+https://github.com/NVlabs/nvdiffrast.git@main",
  "roma",
  "gsplat @ git+https://github.com/nerfstudio-project/gsplat.git@v1.0",
]
dev = ["black", "isort", "ipdb"]

[tool.setuptools.packages.find]
include = ["nerfview"]

[tool.isort]
profile = "black"
